### PR TITLE
OCDSpecExpectation Changes

### PR DESCRIPTION
**Pull request by ericmeyer**
Added support for custom matchers and a matcher for toBeEmptyString

### CODE REVIEW

**Comment by paytonrules** [comment]
Is the failWithMessage method just a refactoring?  failWithMessage doesn't have to be in the header since it's internal

**Comment by ericmeyer** [comment]
Definitely can't be internal if categories need to use it. At least not in the way you had it. I intentionally made a simple fail method like that public to support adding matchers via categories.

Eric

**Comment by paytonrules** [comment]
Two minor things:
1) This won't get merged for a little longer - because it' can't be merged automatically anymore.  That's cause of me refactoring and bug fixing.

2) Can you add a test for failWithMessage?  Since it's public I'd like to see one.  I understand why it's public now.

I really like having the example in there BTW.

**Comment by paytonrules** [comment]
Eric were you able to do this:

2) Can you add a test for failWithMessage? Since it's public I'd like to see one. I understand why it's public now.

I don't see it but my git-hub fu is weak.  Also I'm only awake cause my daughter insisted I get up at 6:15.

**Comment by ericmeyer** [comment]
This pull request made obsolete by new pull request.

**Pull request closed without merging**
